### PR TITLE
Address final reviewer comments.

### PR DESCRIPTION
**Pull request by lindsayad**
You should probably view this PR ignoring whitespace. (I actually forget how to do this with GitHub)

If I can do it quickly enough, I actually want to re-generate the plots on a finer mesh since IMO the coarse mesh plots are not sufficiently converged (despite what I say currently).

### CODE REVIEW

**Comment by gridley** [comment]
I'll add it in a bit, but it may be noteworthy that Dr. Collins is working on putting a 3D cuboidal MSRE into MSR-VERA. When compared with their detailed sub-channel TH models and full-core 152 group MOC neutronics, we should be able to approximate the error introduced by introducing diffusion neutronics and slug flow.

**Comment by lindsayad** [comment]
What do you mean by a bit? It's due today haha

**Comment by gridley** [comment]
Haha, sorry, well, he told me initially that it would take him a matter of hours to put the geometry into VERA. Apparently there have been some complications. So, I think making a note of this next to the openFOAM remark would be good.

**Comment by gridley** [comment]
what do you think of the additional remark @lindsayad?

**Review by andrewryh — APPROVED** [review]

**Review by gridley — APPROVED** [review]
11/10: solid commits

**Comment by katyhuff** [comment]
ignore whitespace with `?w=1`

**Comment by katyhuff** [comment]
LGTM

**Review by katyhuff — APPROVED** [review]

**Pull request merged**
