### PR TITLE
Issue48

### PR DESCRIPTION
**Pull request by katyhuff**
Addresses issue #48 . The document has been rearranged dramatically. This is now the arrangement:

1. Introduction
2. Methods 
2.1 Cyclus
2.2 Nuclear Deployment in the European Union
2.3 Material Flow
2.4 Scenario Specifications
2.5 Reactor Specifications
2.6 Material Definitions
3. Results
3.1 Nuclear Material Inventory
3.2 French SFR Deployment
3.3 Transition Reprocessing Dynamics
4. Conclusion

### CODE REVIEW

**Review by jbae11 — COMMENTED** [review]
@katyhuff 
I think the paper flows much better this way. Thank you. I am not sure about the French SFR deployment being a result though, considering that we are seeing if such an aggressive deployment is possible with our strategy. I think the French SFR deployment is more of an input than a result? I'll merge this and change this around once we talk about it. I'll also fix some table and placing issues as well. 
Thanks!

**Comment by katyhuff** [comment]
> I think the French SFR deployment is more of an input than a result? 

Correct me if I'm wrong, but the deployment schedule for SFRs wasn't explicitly stated in the input file, correct? Sure, it was implicitly stated with the demand growth (flat), but the GrowthRegion nailed down the details when the simulation ran. The ability to deploy the correct number of discrete reactors to meet demand in a timely fashion (as other reactors shut down) may seem trivial, but it's an important capability of cycamore. It was a result given by the tool, not an input value explicitly stated by the user. Perhaps sadly, there are plenty of simulators that don't know how many 600MWe SFRs to deploy when a 1000MWe LWR shuts down.

**Comment by jbae11** [comment]
Actually, I didn't use GrowthRegion to come up with the deployment schedule for SFR, since for GrowthRegion you couldn't specify which reactor to deploy for power. I did it using excel (yikes) but maybe I can write a python script that takes the output file from the first simulation and generate a deployment schedule for SFRs.

**Comment by katyhuff** [comment]
Are you ok with this PR or what, @jbae11 ?

**Comment by jbae11** [comment]
Yeah. The GrowthRegion needs to be figured out later, though.

**Comment by katyhuff** [comment]
Ah, right! The best way to make sure everything that needs to be changed before merging a PR is to say clearly what I should change during the review.

**Comment by katyhuff** [comment]
I'll open another issue to indicate the remaining problem with the GrowthRegion.

**Pull request merged**
