### PR TITLE
Add 3D steady state results, comparison with MSRE, and a scaling study

### PR DESCRIPTION
**Pull request by lindsayad**
I'm feeling pretty good about this paper now. After more review from @katyhuff and a look from @gridley, I would like to submit this somewhere.

### CODE REVIEW

**Comment by katyhuff** [comment]
Excellent. I will read it this weekend! Thanks!

**Comment by lindsayad** [comment]
Part of these changes target #6

**Comment by gridley** [comment]
I believe that "1950s and 60s" should be "1950s and '60s". That's all my input for now, except that I'm thankful my name gets to be on it. :smile:

**Review by katyhuff — APPROVED** [review]

**Comment by katyhuff** [comment]
This looks good. I wonder if there is a way to make the MSRE comparisons in a single plot (e.g. use [yoink](https://github.com/mrterry/yoink) ). The difference between Moltres and MSRE will be more apparent, but the reviewers will prefer it if MSRE and moltres are on plots together.  I'm going to make a pr with some grammatical stuff.

**Pull request merged**
